// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlHealthMonitor.Data;

#nullable disable

namespace UrlHealthMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205102304_AddRecoveryCallbackStatus")]
    partial class AddRecoveryCallbackStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("UrlHealthMonitor.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.MonitoredUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertEmails")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppPoolName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DownSince")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRecoveryAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRecoveryRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRecoveryStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecoveryAction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecoveryCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryWebsiteUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendDownAlert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("GroupId");

                    b.ToTable("MonitoredUrls");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.UrlOutage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DownStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitoredUrlId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecoveredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredUrlId");

                    b.ToTable("UrlOutages");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.UserGroup", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppUserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.AppUser", b =>
                {
                    b.HasOne("UrlHealthMonitor.Models.Role", "Role")
                        .WithMany("AppUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.Group", b =>
                {
                    b.HasOne("UrlHealthMonitor.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.MonitoredUrl", b =>
                {
                    b.HasOne("UrlHealthMonitor.Models.AppUser", null)
                        .WithMany("MonitoredUrls")
                        .HasForeignKey("AppUserId");

                    b.HasOne("UrlHealthMonitor.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.UrlOutage", b =>
                {
                    b.HasOne("UrlHealthMonitor.Models.MonitoredUrl", "MonitoredUrl")
                        .WithMany("UrlOutages")
                        .HasForeignKey("MonitoredUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredUrl");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.UserGroup", b =>
                {
                    b.HasOne("UrlHealthMonitor.Models.AppUser", "AppUser")
                        .WithMany("UserGroups")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrlHealthMonitor.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.AppUser", b =>
                {
                    b.Navigation("MonitoredUrls");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.MonitoredUrl", b =>
                {
                    b.Navigation("UrlOutages");
                });

            modelBuilder.Entity("UrlHealthMonitor.Models.Role", b =>
                {
                    b.Navigation("AppUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
